export const DEFAULT_LOADING_DREAM_ITEMS = [
  'Watch Northern Lights',
  'Learn Salsa Dancing',
  'Run a Half Marathon',
  'Write a Short Story',
  'Take a Solo Trip',
  'Start a Balcony Garden',
  'Learn Basic Guitar',
  'Try Scuba Diving',
  'Cook a 5-Course Meal',
  'Launch a Side Project',
  'Read 20 Books This Year',
  'Take a Pottery Class',
  'Do a Weekend Digital Detox',
  'Learn Conversational Spanish',
  'Hike a Sunrise Trail',
  'Build a Morning Routine',
  'Volunteer for a Local Cause',
  'Create a Photo Journal',
];
